Repository vectra-ai-research/Halberd, pull requests merged in 2025-01, with the labels that each got.

#44 Adds Production Server (hypercorn)
  README.md
  core/Constants.py
  halberd.py
  requirements.txt
  run.py
  version.py
Labels: documentation, enhancement, dependencies, new feature

#46 MS Token Auto Refresh
  attack_techniques/entra_id/entra_device_code_flow_auth.py
  attack_techniques/entra_id/entra_establish_access_as_user.py
  core/entra/entra_token_manager.py
  core/entra/graph_request.py
  requirements.txt
Labels: enhancement, dependencies

#47 Multiple fixes
  assets/halberd.css
  attack_techniques/azure/azure_enumerate_assigned_roles.py
  attack_techniques/base_technique.py
  attack_techniques/entra_id/entra_add_trusted_ip_config.py
  attack_techniques/entra_id/entra_device_code_flow_auth.py
  attack_techniques/entra_id/entra_establish_access_as_user.py
  attack_techniques/m365/m365_deploy_mail_forwarding_rule.py
  core/Functions.py
Labels: bug, enhancement, technique update

#48 3 New Techniques
  attack_techniques/__init__.py
  attack_techniques/azure/azure_extract_cache_tokens.py
  attack_techniques/entra_id/entra_abuse_family_refresh_token.py
  attack_techniques/m365/m365_exfil_sharepoint_data.py
Labels: new technique

#49 New bootstrap class and update logging
  core/Functions.py
  core/bootstrap.py
  core/entra/entra_token_manager.py
  core/entra/graph_request.py
  core/logging/logger.py
  core/logging/logging_config.yml
  core/logging/report.py
  halberd.py
  pages/attack_analyse.py
  run.py
  version.py
Labels: bug, enhancement, wip

#51 Update app callbacks initialization
  halberd.py
  pages/attack.py
  pages/attack_analyse.py
  pages/attack_history.py
  pages/automator.py
  pages/dashboard/entity_map.py
  pages/dashboard/recon_roles.py
  pages/dashboard/recon_users.py
  pages/home.py
  pages/recon.py
  pages/schedules.py
  version.py
Labels: enhancement

#52 Adding New Attack Technique for GCP
  attack_techniques/__init__.py
  attack_techniques/gcp/gcp_enumerate_cloud_storage_buckets.py
  attack_techniques/gcp/gcp_enumerate_cloud_storage_objects.py
  attack_techniques/gcp/gcp_establish_access_as_sa.py
  attack_techniques/gcp/gcp_exfilterate_cloud_storage_objects.py
  requirements.txt
Labels: technique update, new technique

#53 Improve GCP Attack Techniques
  attack_techniques/gcp/gcp_enumerate_cloud_storage_objects.py
  attack_techniques/gcp/gcp_exfilterate_cloud_storage_objects.py
Labels: bug, wip
