Repository vectra-ai-research/Halberd, pull requests merged in 2025-06, with the labels that each got.

#64 Attack Agent File Attachment Support
  agent/attack_agent.py
  assets/halberd.css
  attack_techniques/azure/azure_assign_role.py
  core/bootstrap.py
  pages/attack_agent.py
  run.py
  version.py
Labels: technique update, wip, new feature

#65 feat: New Azure technique
  attack_techniques/__init__.py
  attack_techniques/azure/azure_establish_access_via_device_code.py
Labels: new technique

#63 Add docker support
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement, wip

#67 Adds Halberd app configuration to UI
  agent/attack_agent.py
  halberd.py
  pages/attack_agent.py
Labels: wip, new feature

#66 Github Workflow Optimizations
  .github/workflows/docker.yml
  Dockerfile
Labels: enhancement

#70 refactor(readme): Update readme
  README.md
Labels: documentation

#72 Halberd Attack Agent Improvement
  agent/attack_agent.py
  agent/tools.py
Labels: enhancement, new feature
